"""Controlled solid_dmft / CTHYB launcher (``p3_x_real_launch``).

Writes a ready-to-run sibling ``dmft/`` package and optionally shells out
when a TRIQS / solid_dmft stack is importable or
``SISCFORGE_SOLID_DMFT`` points at an entrypoint.

This is a workstation-first sequential launcher — **not** a jobflow and
**not** a production CTHYB driver. Screening U/J/β/n_cycles stay
screening defaults. TRIQS is never a hard dependency of ``siscforge``.

Automated
    native ``dmft_config.toml`` from :class:`DMFTConfig` + Wannier refs;
    invoke script + ``LAUNCH.md``; optional subprocess when an entrypoint
    is discoverable; parse JSON drop-in, native ``observables_imp*.dat``,
    or ``DMFT_results`` h5 (soft h5py) into ``DMFTResult``.

Operator-owned (honest residual)
    Wannier90 → ``{seed}.h5`` via TRIQS DFTTools when the converter is
    missing or fails; MPI / multi-day QMC wall-time; production U/J/β
    calibration; solid_dmft version matrix.
"""

from __future__ import annotations

import os
import shlex
import shutil
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from siscforge.models.config import DMFTConfig
from siscforge.models.results import WannierResult

ENV_LAUNCHER = "SISCFORGE_SOLID_DMFT"
"""Optional override: executable or command that replaces ``solid_dmft``."""

CONFIG_TOML = "dmft_config.toml"
RUN_SCRIPT = "run_solid_dmft.sh"
LAUNCH_README = "LAUNCH.md"
SIDECAR_NAME = "siscforge_dmft_config.json"
DEFAULT_LOG = "solid_dmft.log"

OBSERVABLES_CANDIDATES: tuple[str, ...] = (
    "observables.json",
    "observables_imp0.json",
    "siscforge_dmft_observables.json",
)

AUTOMATED_STEPS: tuple[str, ...] = (
    "write native dmft_config.toml from WannierResult + DMFTConfig knobs",
    "write run_solid_dmft.sh + LAUNCH.md in the sibling dmft/ workdir",
    "invoke solid_dmft (or SISCFORGE_SOLID_DMFT) when auto_launch and stack present",
    "parse JSON drop-in, then native observables_imp*.dat, then DMFT_results h5",
    "prefer conv_imp*.dat / convergence_obs for DMFTResult.converged "
    "(last-row occupancy fallback)",
)

OPERATOR_OWNED_STEPS: tuple[str, ...] = (
    "Wannier90 → {seed}.h5 via TRIQS DFTTools if the converter is missing",
    "MPI ranks / multi-day CTHYB wall-time on a real workstation or cluster",
    "production U/J/β/n_cycles calibration (screening defaults stay screening)",
    "solid_dmft / TRIQS version matrix validation",
)


@dataclass
class LaunchOutcome:
    """Result of one solid_dmft (or stub) subprocess attempt."""

    returncode: int
    command: list[str] = field(default_factory=list)
    log_path: str | None = None
    stdout_tail: str = ""
    timed_out: bool = False
    error: str | None = None
    source: str = ""

    @property
    def ok(self) -> bool:
        return self.returncode == 0 and not self.timed_out and self.error is None


def _toml_str(value: str) -> str:
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'


def _toml_bool(value: bool) -> str:
    return "true" if value else "false"


def render_dmft_config_toml(
    cfg: DMFTConfig,
    *,
    u: float,
    j: float,
    seedname: str,
    jobname: str = "out",
) -> str:
    """Render a screening-default solid_dmft ``dmft_config.toml``.

    One-shot (not charge self-consistent). Solver type is ``cthyb`` for
    both ``solid_dmft`` and ``cthyb`` campaign knobs — solid_dmft is the
    wrapper; CTHYB is the impurity solver.
    """
    solver_type = "cthyb"
    lines = [
        "# Generated by siscforge p3_x_real_launch.",
        "# Screening defaults — not production CTHYB settings.",
        "# See LAUNCH.md for automated vs operator-owned steps.",
        "",
        "[general]",
        f"seedname = {_toml_str(seedname)}",
        f"jobname = {_toml_str(jobname)}",
        f"csc = {_toml_bool(False)}",
        'h_int_type = "kanamori"',
        f"U = {float(u):g}",
        f"J = {float(j):g}",
        f"beta = {float(cfg.beta):g}",
        f"n_iter_dmft = {int(cfg.n_loops)}",
        "dc = true",
        "dc_type = 1",
        "dc_dmft = false",
        "calc_energies = false",
        "",
        "[solver]",
        f"type = {_toml_str(solver_type)}",
        f"n_warmup_cycles = {int(cfg.n_warmup_cycles)}",
        f"n_cycles_tot = {int(cfg.n_cycles)}",
        "# n_cycles / n_warmup / n_loops are thin workstation knobs.",
        "",
    ]
    return "\n".join(lines)


def render_run_script(*, seedname: str, toml_name: str = CONFIG_TOML) -> str:
    """POSIX script an operator (or this launcher) can exec in ``dmft/``."""
    return f"""#!/bin/sh
# Generated by siscforge p3_x_real_launch. See LAUNCH.md.
set -eu
cd "$(dirname "$0")"
SEED={shlex.quote(seedname)}
TOML={shlex.quote(toml_name)}

if [ ! -f "$SEED.h5" ]; then
  echo "siscforge: missing $SEED.h5 (solid_dmft one-shot input)." >&2
  echo "Convert Wannier90 artifacts with TRIQS DFTTools, then re-run." >&2
  echo "See LAUNCH.md." >&2
  exit 2
fi

if [ -n "${{SISCFORGE_SOLID_DMFT:-}}" ]; then
  exec ${{SISCFORGE_SOLID_DMFT}} "$TOML"
fi

if command -v solid_dmft >/dev/null 2>&1; then
  exec solid_dmft "$TOML"
fi

exec python -c "from solid_dmft.main import main; main(['solid_dmft', '$TOML'])"
"""


def render_launch_readme(
    *,
    seedname: str,
    wannier_work_dir: str | None,
    wannier_chk_path: str | None,
) -> str:
    wdir = wannier_work_dir or "(no Wannier work_dir attached)"
    chk = wannier_chk_path or "(no .chk path attached)"
    automated = "\n".join(f"- {s}" for s in AUTOMATED_STEPS)
    owned = "\n".join(f"- {s}" for s in OPERATOR_OWNED_STEPS)
    return f"""# solid_dmft run package (siscforge p3_x_real_launch)

This sibling `dmft/` directory is the only tree siscforge writes for DMFT.
Finished DFT+U / Wannier artifacts are sacred and are never deleted here.

## What siscforge automated

{automated}

## What remains operator-owned

{owned}

## Invoke (when siscforge did not already launch)

```bash
# from this directory
sh run_solid_dmft.sh
# or, if the stack is on PATH:
solid_dmft {CONFIG_TOML}
```

Optional override: `SISCFORGE_SOLID_DMFT=/path/to/wrapper`.

## Wannier → h5 (one-shot input)

solid_dmft one-shot reads `{{seedname}}.h5`. Seedname: `{seedname}`.

Wannier refs from this campaign:

- work_dir: `{wdir}`
- chk: `{chk}`

If `{seedname}.h5` is not already here, convert Wannier90 output with
TRIQS DFTTools (typical):

```python
from triqs_dft_tools.converters.wannier90 import Wannier90Converter
# run in the Wannier work directory that holds .win / .chk / .amn / .mmn
Wannier90Converter(seedname="{seedname}").convert_dft_input()
```

Then copy `{seedname}.h5` into this `dmft/` directory (do not move the
Wannier originals). siscforge will try this converter automatically when
`triqs_dft_tools` is importable.

## Observables discovery / resume

After a launch (or on re-invoke) siscforge looks for occupancy / filling
in this order — first *usable* source wins:

1. JSON drop-in (preferred; no TRIQS required):
   - `observables.json`
   - `observables_imp0.json`
   - `siscforge_dmft_observables.json`
2. Native solid_dmft text tables such as `observables_imp0.dat`
   (also `out/observables_imp0.dat`, `observables_imp0_up.dat` +
   `_down.dat`, and close filename variants).
3. HDF5 archive under common `DMFT_results` / impurity-observable keys,
   **when** `h5py` (or a TRIQS helper) is importable — still soft.

A successful native `.dat` / h5 parse materializes a compatible
`observables.json` in this directory so later resume does not need
TRIQS or h5py again.

## Convergence (`DMFTResult.converged`)

Precedence (first matching row wins):

1. Explicit JSON `converged` / `success` / `job_done` on an **operator**
   drop-in. Bridged `observables.json` (`siscforge_bridge`) is *not*
   treated as explicit so a live conv table can override it.
2. Real solid_dmft signals when usable:
   - `conv_imp*.dat` (also `out/`, close name variants)
   - h5 `DMFT_results/convergence_obs` (soft `h5py`)
3. Stored native-bridge verdict if those files are gone on resume.
4. Last-row / occupancy heuristic — occupancy-only parses stay
   non-failed when conv diagnostics are missing.
5. Otherwise conservative `false`.

Screening residual cutoffs (documented, not production CTHYB):
`d_imp_occ=0.02`, `d_Gimp=d_G0=d_Sigma=0.05`. `d_mu` is recorded
but informational. Missing conv files never invent a hard failure.

Pairing keys (`leading_pairing_eigenvalue`, `pairing_symmetry`) flow
into P3.4 when present. Exotic solid_dmft layouts can still drop a
hand-written JSON.

## Honesty

Screening U/J/β/n_cycles/n_loops are thin workstation knobs, not a
literature-validated nickelate CTHYB setup. A passing launch is not an
NdNiO₂ recovery claim.
"""


def write_solid_dmft_run_package(
    work_dir: Path,
    cfg: DMFTConfig,
    *,
    wannier: WannierResult | None,
    u: float,
    j: float,
    extra: dict[str, Any] | None = None,
) -> dict[str, str]:
    """Write toml + invoke script + LAUNCH.md. Returns path map."""
    del extra  # reserved for callers that stamp sidecar extras separately
    work_dir.mkdir(parents=True, exist_ok=True)
    seedname = (cfg.seedname or "siscforge").strip() or "siscforge"
    toml_text = render_dmft_config_toml(cfg, u=u, j=j, seedname=seedname)
    toml_path = work_dir / CONFIG_TOML
    toml_path.write_text(toml_text, encoding="utf-8")

    script_path = work_dir / RUN_SCRIPT
    script_path.write_text(render_run_script(seedname=seedname), encoding="utf-8")
    try:
        script_path.chmod(script_path.stat().st_mode | 0o111)
    except OSError:
        pass

    readme_path = work_dir / LAUNCH_README
    readme_path.write_text(
        render_launch_readme(
            seedname=seedname,
            wannier_work_dir=wannier.work_dir if wannier is not None else None,
            wannier_chk_path=wannier.chk_path if wannier is not None else None,
        ),
        encoding="utf-8",
    )
    return {
        "toml": str(toml_path),
        "script": str(script_path),
        "readme": str(readme_path),
        "seedname": seedname,
    }


def discover_solid_dmft_command(
    *,
    toml_name: str = CONFIG_TOML,
) -> tuple[list[str] | None, str]:
    """Locate an invoke command. Never imports TRIQS unless already on path.

    Order: ``SISCFORGE_SOLID_DMFT`` → ``solid_dmft`` on PATH →
    ``solid_dmft.main`` via the current interpreter.
    """
    raw = (os.environ.get(ENV_LAUNCHER) or "").strip()
    if raw:
        cmd = shlex.split(raw)
        return cmd, f"env:{ENV_LAUNCHER}"

    exe = shutil.which("solid_dmft")
    if exe:
        return [exe, toml_name], "cli:solid_dmft"

    try:
        import solid_dmft.main  # noqa: F401
    except ImportError:
        return None, "not_found"
    snippet = f"from solid_dmft.main import main; main(['solid_dmft', {toml_name!r}])"
    return [sys.executable, "-c", snippet], "python:solid_dmft.main"


def invoke_solid_dmft(
    command: list[str],
    work_dir: Path,
    *,
    timeout_s: float | None = None,
    log_name: str = DEFAULT_LOG,
    source: str = "",
) -> LaunchOutcome:
    """Run *command* in *work_dir*; capture log. Never raises on rc != 0."""
    work_dir.mkdir(parents=True, exist_ok=True)
    log_path = work_dir / log_name
    try:
        proc = subprocess.run(
            command,
            cwd=str(work_dir),
            capture_output=True,
            text=True,
            timeout=timeout_s,
            check=False,
        )
    except subprocess.TimeoutExpired as exc:
        blob = ((exc.stdout or "") + "\n" + (exc.stderr or "")).strip()
        tail = f"timed out after {timeout_s:g}s\n{blob}".strip()
        log_path.write_text(tail + "\n", encoding="utf-8")
        return LaunchOutcome(
            returncode=124,
            command=list(command),
            log_path=str(log_path),
            stdout_tail=tail[-800:],
            timed_out=True,
            error=f"solid_dmft timed out after {timeout_s:g}s",
            source=source,
        )
    except OSError as exc:
        msg = f"cannot execute solid_dmft ({exc})"
        log_path.write_text(msg + "\n", encoding="utf-8")
        return LaunchOutcome(
            returncode=127,
            command=list(command),
            log_path=str(log_path),
            stdout_tail=msg,
            error=msg,
            source=source,
        )

    out = (proc.stdout or "") + ("\n" + proc.stderr if proc.stderr else "")
    log_path.write_text(out, encoding="utf-8")
    return LaunchOutcome(
        returncode=int(proc.returncode),
        command=list(command),
        log_path=str(log_path),
        stdout_tail=out.strip()[-800:],
        source=source,
        error=None if proc.returncode == 0 else f"solid_dmft rc={proc.returncode}",
    )


def find_observables_file(work_dir: Path) -> Path | None:
    """Return the first JSON drop-in in *work_dir* (legacy helper).

    Native ``.dat`` / h5 discovery lives in
    :func:`siscforge.calculators.qe.dmft_observables.discover_dmft_metrics`.
    """
    for name in OBSERVABLES_CANDIDATES:
        cand = work_dir / name
        if cand.is_file():
            return cand
    return None


def find_existing_h5(work_dir: Path, seedname: str, wannier: WannierResult | None) -> Path | None:
    """Locate an existing ``{seed}.h5`` without modifying anything."""
    direct = work_dir / f"{seedname}.h5"
    if direct.is_file():
        return direct
    search: list[Path] = []
    if wannier is not None and wannier.work_dir:
        search.append(Path(wannier.work_dir))
    search.append(work_dir)
    for root in search:
        named = root / f"{seedname}.h5"
        if named.is_file():
            return named
        if root.is_dir():
            matches = sorted(root.glob("*.h5"))
            if matches:
                return matches[0]
    return None


def try_convert_wannier90_to_h5(
    wannier_dir: Path,
    seedname: str,
) -> tuple[Path | None, str]:
    """Best-effort DFTTools Wannier90 → h5. Soft: never raises."""
    converter = None
    source = ""
    try:
        from triqs_dft_tools.converters.wannier90 import (  # type: ignore[import-not-found]
            Wannier90Converter,
        )

        converter = Wannier90Converter
        source = "triqs_dft_tools"
    except ImportError:
        try:
            from triqs.dft_tools.converters.wannier90 import (  # type: ignore[import-not-found]
                Wannier90Converter,
            )

            converter = Wannier90Converter
            source = "triqs.dft_tools"
        except ImportError:
            return None, "DFTTools Wannier90Converter not importable"

    cwd = Path.cwd()
    try:
        os.chdir(wannier_dir)
        conv = converter(seedname=seedname)
        conv.convert_dft_input()
    except Exception as exc:  # noqa: BLE001 — converter is optional
        return None, f"{source} Wannier90Converter failed: {exc}"
    finally:
        try:
            os.chdir(cwd)
        except OSError:
            pass

    h5 = wannier_dir / f"{seedname}.h5"
    if h5.is_file():
        return h5, f"{source}_converter"
    return None, f"{source} converter ran but {seedname}.h5 was not written"


def stage_h5_archive(
    work_dir: Path,
    cfg: DMFTConfig,
    wannier: WannierResult | None,
    *,
    convert: bool = True,
) -> dict[str, Any]:
    """Copy (never move) an h5 into *work_dir* when one can be found.

    Sacred-upstream: Wannier originals are left in place.
    """
    seedname = (cfg.seedname or "siscforge").strip() or "siscforge"
    dest = work_dir / f"{seedname}.h5"
    info: dict[str, Any] = {
        "seedname": seedname,
        "dest": str(dest),
        "found": False,
        "method": None,
        "source": None,
        "notes": "",
    }
    existing = find_existing_h5(work_dir, seedname, wannier)
    if existing is None and convert and wannier is not None and wannier.work_dir:
        converted, note = try_convert_wannier90_to_h5(Path(wannier.work_dir), seedname)
        info["notes"] = note
        existing = converted
        if converted is not None:
            info["method"] = "dfttools_convert"
    if existing is None:
        if not info["notes"]:
            info["notes"] = f"missing {seedname}.h5; convert Wannier90 artifacts (see LAUNCH.md)"
        return info

    info["source"] = str(existing)
    if existing.resolve() != dest.resolve():
        try:
            shutil.copy2(existing, dest)
            info["method"] = info["method"] or "copied"
        except OSError as exc:
            info["notes"] = f"failed to copy h5 into dmft/: {exc}"
            return info
    else:
        info["method"] = info["method"] or "already_in_place"
    info["found"] = dest.is_file()
    if info["found"] and not info["notes"]:
        info["notes"] = f"staged {dest.name} via {info['method']}"
    return info
